pipeline {
    agent any
    stages{
        stage('Docker Build') {
            steps {
      	        sh 'docker build -t ajaymakode/my-alpine:v1$""BUILD_ID"" .'
            }
        }
        stage('Docker Push') {
            steps {
      	        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
        	      sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                  sh 'docker push ajaymakode/my-alpine:v1$""BUILD_ID""'
                }
            }
    
        }
    }
  }