pipeline {
    stage('Docker Build') {
    	agent any
      steps {
      	sh 'docker build -t ajaymakode/my-alpine:v1$BUILD_ID .'
      }
    }
    stage('Docker Push') {
    	agent any
      steps {
      	withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
        	sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push shanem/spring-petclinic:v1$BUILD_ID'
        }
      }
    }
  }